use hotel;

INSERT INTO `hotel`(`name`, `location`, `numberOfRooms`, `numberOfStars`, `capacity`, `services_type`, `facilities`) VALUES  ("The Hidden Paradise", "seaside", 250, 5, "large", "ALL_INCLUSIVE", "POOL")
INSERT INTO `hotel`(`name`, `location`, `numberOfRooms`, `numberOfStars`, `capacity`, `services_type`, `facilities`) VALUES  ("Ayana Resort&Spa", "seaside", 120, 4, "low", "DEMIPENSIUNE", "GYM")
INSERT INTO `hotel`(`name`, `location`, `numberOfRooms`, `numberOfStars`, `capacity`, `services_type`, `facilities`) VALUES  ("Silver Mountain Resort & SPA", "mountain", 180, 4, "large", "BREAKFAST", "POOL")
INSERT INTO `hotel`(`name`, `location`, `numberOfRooms`, `numberOfStars`, `capacity`, `services_type`, `facilities`) VALUES  ("Teleferic Grand Hotel", "mountain", 170, 4, "medium", "ALL_INCLUSIVE", "GYM")
INSERT INTO `hotel`(`name`, `location`, `numberOfRooms`, `numberOfStars`, `capacity`, `services_type`, `facilities`) VALUES  ("Four Seasons", "seaside", 200, 4, "large", "BREAKFAST", "RESTAURANT")
INSERT INTO `hotel`(`name`, `location`, `numberOfRooms`, `numberOfStars`, `capacity`, `services_type`, `facilities`) VALUES  ("The Westin Resort & Spa Ubud", "seaside", 150, 4, "medium", "ALL_INCLUSIVE", "POOL")
INSERT INTO `hotel`(`name`, `location`, `numberOfRooms`, `numberOfStars`, `capacity`, `services_type`, `facilities`) VALUES("Aro Palace", "mountain", 170, 5, "large", "BREAKFAST", "GYM")
INSERT INTO `hotel`(`name`, `location`, `numberOfRooms`, `numberOfStars`, `capacity`, `services_type`, `facilities`) VALUES ("ART Hotel", "seaside", 100, 4, "low", "DEMIPENSIUNE", "POOL")
INSERT INTO `hotel`(`name`, `location`, `numberOfRooms`, `numberOfStars`, `capacity`, `services_type`, `facilities`) VALUES ("Castelnor", "seaside", 80, 4, "low", "DEMIPENSIUNE", "RESTAURANT")
INSERT INTO `hotel`(`name`, `location`, `numberOfRooms`, `numberOfStars`, `capacity`, `services_type`, `facilities`) VALUES ("Mandachi Hotel & SPA", "mountain", 150, 5, "medium", "ALL_INCLUSIVE", "RESTAURANT")
INSERT INTO `hotel`(`name`, `location`, `numberOfRooms`, `numberOfStars`, `capacity`, `services_type`, `facilities`) VALUES ("Ramada Plaza", "seaside", 180, 4, "large", "ALL_INCLUSIVE", "POOL")
INSERT INTO `hotel`(`name`, `location`, `numberOfRooms`, `numberOfStars`, `capacity`, `services_type`, `facilities`) VALUES ("Grand Hotel", "mountain", 150, 5, "medium", "BREAKFAST", "SPA")


INSERT INTO `room`(`type`, `number`, `price`) VALUES  ("double", 23, 349.9)
INSERT INTO `room`(`type`, `number`, `price`) VALUES  ("double", 36, 300)
INSERT INTO `room`(`type`, `number`, `price`) VALUES  ("single", 64, 259.9)
INSERT INTO `room`(`type`, `number`, `price`) VALUES  ("twin", 7, 199.9)
INSERT INTO `room`(`type`, `number`, `price`) VALUES  ("studio", 57, 499.9)
INSERT INTO `room`(`type`, `number`, `price`) VALUES  ("suite", 80, 350)
INSERT INTO `room`(`type`, `number`, `price`) VALUES  ("single", 120, 250)
INSERT INTO `room`(`type`, `number`, `price`) VALUES  ("twin", 115, 200)
INSERT INTO `room`(`type`, `number`, `price`) VALUES  ("suite", 50, 399.9)
INSERT INTO `room`(`type`, `number`, `price`) VALUES  ("studio", 75, 380)

INSERT INTO `customer`(`firstName`, `lastName`, `age`, `gender`) VALUES  ("Horatiu", "Pop", 26, "M")
INSERT INTO `customer`(`firstName`, `lastName`, `age`, `gender`) VALUES  ("Andreea", "Pop", 25, "F")
INSERT INTO `customer`(`firstName`, `lastName`, `age`, `gender`) VALUES  ("David", "Stancu", 35, "M")
INSERT INTO `customer`(`firstName`, `lastName`, `age`, `gender`) VALUES  ("Stefania", "Onciu", 19, "F")
INSERT INTO `customer`(`firstName`, `lastName`, `age`, `gender`) VALUES  ("Andrei", "Stefanescu", 40, "M")
INSERT INTO `customer`(`firstName`, `lastName`, `age`, `gender`) VALUES  ("Sebastian", "Olar", 22, "M")
INSERT INTO `customer`(`firstName`, `lastName`, `age`, `gender`) VALUES  ("Sofia", "Codrin", 32, "F")
INSERT INTO `customer`(`firstName`, `lastName`, `age`, `gender`) VALUES  ("Katia", "Popescu", 28, "F")
INSERT INTO `customer`(`firstName`, `lastName`, `age`, `gender`) VALUES  ("Diana", "Bacaian", 27, "F")

INSERT INTO `booking`(`numberOfPerson`, `numberOfDays`, `startDate`, `endDate`, `room_type`, `price`) VALUES (2, 5, '2021-03-06', '2021-03-11', "DOUBLE", 1500)
INSERT INTO `booking`(`numberOfPerson`, `numberOfDays`, `startDate`, `endDate`, `room_type`, `price`) VALUES (2, 7, '2021-05-20', '2021-05-27', "TWIN", 2000)
INSERT INTO `booking`(`numberOfPerson`, `numberOfDays`, `startDate`, `endDate`, `room_type`, `price`) VALUES (4, 10, '2021-08-15', '2021-08-25', "STUDIO", 5199.9)
INSERT INTO `booking`(`numberOfPerson`, `numberOfDays`, `startDate`, `endDate`, `room_type`, `price`) VALUES (3, 8, '2021-07-10', '2021-07-18', "SUITE", 3500)
INSERT INTO `booking`(`numberOfPerson`, `numberOfDays`, `startDate`, `endDate`, `room_type`, `price`) VALUES (1, 3, '2021-06-14', '2021-06-17', "SINGLE", 800)
INSERT INTO `booking`(`numberOfPerson`, `numberOfDays`, `startDate`, `endDate`, `room_type`, `price`) VALUES (5, 4, '2021-05-10', '2021-05-14', "STUDIO", 2809.9)

